curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/.gitignore -o .gitignore
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/readme.md -o readme.md
curl -L --create-dirs "https://anonymous.4open.science/r/dna-esa-BED6/Read simulation Using ART.pdf" -o "Read simulation Using ART.pdf"
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/pyproject.toml -o pyproject.toml
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/train.py -o train.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/configs/default_config.py -o configs/default_config.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/configs/default_config.py -o configs/default_config.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/docs/examples/embedding_space.ipynb -o docs/examples/embedding_space.ipynb
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/docs/extract.py -o docs/extract.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/aligners/__init__.py -o evaluate/aligners/__init__.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/aligners/bowtie2.py -o evaluate/aligners/bowtie2.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/aligners/bwamem2.py -o evaluate/aligners/bwamem2.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/aligners/minimap2.py -o evaluate/aligners/minimap2.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/aligners/smith_waterman.py -o evaluate/aligners/smith_waterman.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/configs/data_recipes.yaml -o evaluate/configs/data_recipes.yaml
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/configs/model_checkpoints.yaml -o evaluate/configs/model_checkpoints.yaml
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/configs/raw.yaml -o evaluate/configs/raw.yaml
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/data/chromosome_2/ch2_genes.csv -o evaluate/data/chromosome_2/ch2_genes.csv
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/figures/baselines.png -o evaluate/figures/baselines.png
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/figures/baselines2.png -o evaluate/figures/baselines2.png
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/figures/fixed_ir_dr.png -o evaluate/figures/fixed_ir_dr.png
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/figures/fixed_qs.png -o evaluate/figures/fixed_qs.png
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/figures/fixed_qs_dr.png -o evaluate/figures/fixed_qs_dr.png
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/figures/topk.png -o evaluate/figures/topk.png
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/others/StrobeAlign.ipynb -o evaluate/others/StrobeAlign.ipynb
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/others/bound.py -o evaluate/others/bound.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/others/evaluate_bound.ipynb -o evaluate/others/evaluate_bound.ipynb
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/others/multi-store_accuracy.py -o evaluate/others/multi-store_accuracy.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/others/multi-store_permute.py -o evaluate/others/multi-store_permute.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/others/test_acc.ipynb -o evaluate/others/test_acc.ipynb
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/others/test_accuracy.py -o evaluate/others/test_accuracy.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/others/test_clustering.ipynb -o evaluate/others/test_clustering.ipynb
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/others/test_clustering.py -o evaluate/others/test_clustering.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/others/test_permute.py -o evaluate/others/test_permute.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/README.md -o evaluate/README.md
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/__init__.py -o evaluate/__init__.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/alignment_metrics.py -o evaluate/alignment_metrics.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/baseline.ipynb -o evaluate/baseline.ipynb
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/helpers.py -o evaluate/helpers.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/inference_model_helpers.py -o evaluate/inference_model_helpers.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/inference_models.py -o evaluate/inference_models.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/pinecone_store.py -o evaluate/pinecone_store.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/stage_upstream.py -o evaluate/stage_upstream.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/test_accuracy_fast.py -o evaluate/test_accuracy_fast.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/test_alignment.ipynb -o evaluate/test_alignment.ipynb
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/test_custom_generalization_accuracy.py -o evaluate/test_custom_generalization_accuracy.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/test_custom_generalization_permute.py -o evaluate/test_custom_generalization_permute.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/test_permute_fast.py -o evaluate/test_permute_fast.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/test_permutes.ipynb -o evaluate/test_permutes.ipynb
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/evaluate/upsert.py -o evaluate/upsert.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/XXXX-2/__init__.py -o src/XXXX-2/__init__.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/XXXX-2/__main__.py -o src/XXXX-2/__main__.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/XXXX-2/config_schema.py -o src/XXXX-2/config_schema.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/XXXX-2/dataset.py -o src/XXXX-2/dataset.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/XXXX-2/main.py -o src/XXXX-2/main.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/XXXX-2/model.py -o src/XXXX-2/model.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/XXXX-2/similarity.py -o src/XXXX-2/similarity.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/XXXX-2/simulate.py -o src/XXXX-2/simulate.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/XXXX-2/tokenizer.py -o src/XXXX-2/tokenizer.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/XXXX-2/trainer.py -o src/XXXX-2/trainer.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/XXXX-2/utils.py -o src/XXXX-2/utils.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/model/tokenizers/dna_tokenizer_10_no_padding.json -o src/model/tokenizers/dna_tokenizer_10_no_padding.json
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/model/tokenizers/dna_tokenizer_10k.json -o src/model/tokenizers/dna_tokenizer_10k.json
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/src/model/tokenizers/dna_tokenizer_20_no_padding.json -o src/model/tokenizers/dna_tokenizer_20_no_padding.json
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/tests/data/sample_simulated_reads.aln -o tests/data/sample_simulated_reads.aln
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/tests/data/sample_simulated_reads.fq -o tests/data/sample_simulated_reads.fq
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/tests/data/sample_simulated_reads.sam -o tests/data/sample_simulated_reads.sam
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/tests/__init__.py -o tests/__init__.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/tests/test_dataset.py -o tests/test_dataset.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/tests/test_main.py -o tests/test_main.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/tests/test_model.py -o tests/test_model.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/tests/test_simulate.py -o tests/test_simulate.py
curl -L --create-dirs https://anonymous.4open.science/r/dna-esa-BED6/tests/test_utils.py -o tests/test_utils.py
