ch2: "/home/pholur/dnaesa/evaluate/data/chromosome_2/NC_000002.fasta"
ch3: "/home/pholur/dnaesa/evaluate/data/chromosome_3/NC_000003.fasta"

all: "../General_Models/data/all/chm13v2.0.fa"  

ch11: "../General_Models/data/chr11/chr11.fasta"

chY: "../General_Models/data/chrY/chrY.fasta"

chimp2A: "../General_Models/data/chimp_2a/chimp_2a.fasta"
chimp2B: "../General_Models/data/chimp_2b/chimp_2b.fasta"

rat1: "../General_Models/data/rat1/rat1.fasta"
rat2: "../General_Models/data/rat2/rat2.fasta"

ch23Y: "../General_Models/data/chr23Y/chr23Y.fasta"

chM: "../General_Models/data/chM/chM.fasta"